name: Deploy Site

on:
  push:
    branches: ["main"]

permissions:
  # IMPORTANT: this enables automatic authentication to the server
  id-token: write
  contents: read

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: internet-golf/deploy@v0.1.9
      - run: |
          cd singlehanded
          corepack enable
          yarn install
          yarn generate
          golf create-deployment singlehanded.stuffedanimal.family --auth github-oidc
          golf deploy-content singlehanded.stuffedanimal.family --auth github-oidc --files ./dist
